### ISSUE TITLE
你那个网站下面的文字怎么弄的，可以说说吗？

### ISSUE THREAD

**Issue by Hello-XPH** [qkqpttgf/OneDrive_SCF#12]
![捕获](https://user-images.githubusercontent.com/56664327/66977787-d72b0100-f0d9-11e9-9839-783e41544473.PNG)

**Comment by qkqpttgf** [comment]
请新建一个readme.md的文件，里面随便写点啥，就可以了。
------
还有，请不要3连击……

**Comment by Hello-XPH** [comment]
创建了一样不行

**Comment by Hello-XPH** [comment]
![image](https://user-images.githubusercontent.com/56664327/67071125-568d0300-f1b4-11e9-97ca-5404a400f96e.png)

**Comment by qkqpttgf** [comment]
你的思路很好很强大，我有点跟不上……
这个文件请去OD里面新建……

**Comment by Hello-XPH** [comment]
额，好吧。我也不知道，你说的把文件放哪里。谢谢啦😊
