### ISSUE TITLE
关于新功能的提议

### ISSUE THREAD

**Issue by MCSeekeri** [qkqpttgf/OneDrive_SCF#16]
这是我关于这个项目新功能的一点小建议
- 开放特定文件夹游客自由上传文件(参考Onedrive本身的分享链接)
- 细分的文件权限管理(这个比较麻烦,估计不能实现)
- 分开上传密码和管理密码,上传密码只能上传文件(和1搭配)
目前就暂时想到这么多了....
当然,不能实现也没问题....

**Comment by qkqpttgf** [comment]
……………………
我8月16日就做了游客上传了，你都不看的吗？
权限，只能游客跟管理分开，其它的没办法指定。

**Comment by MCSeekeri** [comment]
emm
我看到了,那个分支,但是我更新代码之后并没有出现选择文件按钮啊...

另外我的意思是列出文件内容并支持游客上传

**Comment by qkqpttgf** [comment]
主人上传跟游客上传不一样。
怎么让游客上传请自行摸索。

**Comment by MCSeekeri** [comment]
是的我知道,作为一个Github用户,我知道要读README.md或者README_CN.md。

我的意思不是说一个扔完文件就跑的图床,更近似于一个Mod分享社区,每个人都可以上传文件并查看别人的文件.....差不多就是群文件吧。

(我知道你大概被那些傻乎乎就照着某个不知名网站的教程还跑来和你要售后的人惹烦了,但是也许你可以试着冷静一下)

**Comment by qkqpttgf** [comment]
呃，为我的口气抱歉。
我做的就是隐藏的，以MD5命名的丢文件的地方，一开始就是为了隐藏。
如果还要看到其它人的文件，那后台要改好几个地方（抚脸，我应该不会这样动它了。
如果是MOD的话，可能你们原来就有交流的地方，把这个当成附件存放地的网盘不是更好~因为这个程序本身就不存在交流。

**Comment by MCSeekeri** [comment]
是的是的就是作为群文件(大概)存在,但是是可以让所有成员上传,而不是几个管理员。
我们是有个群作为交流的,但是因为某些原因一些东西没法传到群文件里,所以我才用这一个。
行吧,我试着自学php改改代码

**Comment by qkqpttgf** [comment]
那现在的游客上传功能应该已经够你用了，不用改。
