### ISSUE TITLE
请教下报错问题

### ISSUE THREAD

**Issue by ben4399** [qkqpttgf/OneDrive_SCF#17]
{"errorCode":-1,"errorMessage":"Task timed out after 3 seconds"}

经常访问爆出这个错误，使用过教育版本office365，让腾讯云选择香港，也是报错。使用个人账号地区设置中国，腾讯云函数选择上海也是经常访问报错这个，请教下是不是我哪里设置的有问题。

**Comment by ben4399** [comment]
是不是环境变量的key未设置完整，以个人账户为例、我只设置了t1-t4、sitename、admin、passfile

**Comment by ben4399** [comment]
好像腾讯云函数设置的超时时间为3秒，设置低了，现在调成180秒好像还不错。。。emmm

**Comment by qkqpttgf** [comment]
自问自答可还行HHHHH
嗯，默认3秒，看我操作视频里面有改30秒的。
