### ISSUE TITLE
文件预览问题

### ISSUE THREAD

**Issue by MCSeekeri** [qkqpttgf/OneDrive_SCF#18]
![](https://upload.cc/i1/2019/11/02/GwbAz5.jpg
 )
![](https://upload.cc/i1/2019/11/02/DbKgft.jpg
 )

貌似文件预览出现了大问题
我用Onedrive自带的也打不开

**Comment by qkqpttgf** [comment]
你用的什么浏览器？
是这样的，blv跟flv在手机chrome上不能打开，只能在UC或夸克等某些手机浏览器打开。
具体什么原理不太清楚。

**Comment by MCSeekeri** [comment]
我自己的Onedrive里mp4也打不开了,啧

浏览器是via,基本就是个壳,里面的是Android WebView

至于原因...可能是这些浏览器会替换现有的播放器,我的小米就是这样



在 qkqpttgf <notifications@github.com>，2019年11月3日 下午12:46写道：

你用的什么浏览器？
是这样的，blv跟flv在手机chrome上不能打开，只能在UC或夸克等某些手机浏览器打开。
具体什么原理不太清楚。
