### ISSUE TITLE
选择Onedrive版本 不跳转？

### ISSUE THREAD

**Issue by Nine55** [qkqpttgf/OneDrive_SCF#19]
稍等3秒
确认Onedrive版本
为国际版（支持商业版与个人版）

有跳回来啦了 ？

**Comment by qkqpttgf** [comment]
请去看一眼环境变量里面有没有Onedrive_ver，如果有，请再等一会再次安装。
如果没有，1，请确认你的Secret Id跟Key都对，有没有多空格，
2，确认你的长链接，第一个小数点后面是不是ap-hongkong形式的，如果是广州的gz，目前没办法，我在跟腾讯提了，可以先换地区。

**Comment by Nine55** [comment]
命名空间的问题，都放第一个空间就没问题了.

**Comment by Nine55** [comment]
> 请去看一眼环境变量里面有没有Onedrive_ver，如果有，请再等一会再次安装。
> 如果没有，1，请确认你的秘密ID跟Key都对，有没有多空格，
> 2，确认你的长链接，第一个小数点后面是不是AP-香港形式的，如果是广州的广州，目前没办法，我在跟腾讯提了，可以先换地区。

嗯，这个没问题了，但是一键更新后，加密的目录全失效了。重新上传文件有没问题了，更新有点小问题。

**Comment by qkqpttgf** [comment]
我的锅，现在加密修复了

**Comment by qkqpttgf** [comment]
关于namespace，刚刚更新了一下，邀请你再用其它命名空间试一下！
