### ISSUE TITLE
页面加密设置加密目录，不加密文件

### ISSUE THREAD

**Issue by yoogg** [qkqpttgf/OneDrive_SCF#22]
可以设置只加密目录，不加密文件吗？可以方便设置外链，而不泄露同一目录其他文件

**Comment by qkqpttgf** [comment]
那你找到目前版本365行，把if中的跳转拿出来，不要if判断了。
不过你这样的话，把你的passfile藏好，不然别人可以直接下载passfile知道你密码～～

**Comment by yoogg** [comment]
没有找到，可以麻烦写一下哪段代码要改成什么吗？或者可以更新把这个设置添加到环境变量吗？

**Comment by qkqpttgf** [comment]
在几天前的365行……几天你都不看……
在目前版本的279行，请速度查看，不然过几天又不是279了。把return前的英文删掉就达到你目的了。
你的issue有空可以close一下。
