### ISSUE TITLE
可以增加SharePoint组文档库的支持吗？

### ISSUE THREAD

**Issue by yoogg** [qkqpttgf/OneDrive_SCF#23]
OneDrive商业版就是SharePoint 的文档库，可以增加对其他组文件库的读取吗？SharePoint组的空间更大，而且可以设置多人账号登陆，管理共享更方便

**Comment by qkqpttgf** [comment]
没懂，不会………

**Comment by yoogg** [comment]
就是登录商业版office365后，有个人存储空间和团队空间。
OneDrive存储位置是https://xxx-my.sharepoint.com/personal/xxx_xxx_com/_layouts/15/onedrive.aspx
Sharepoint的组团队文档是
https://xxx.sharepoint.com/sites/xxx/Shared Documents/Forms/AllItems.aspx

**以下是微软官方的API：**
https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/?view=odsp-graph-online

**Comment by qkqpttgf** [comment]
应该不会做了，过几年再考虑
