### ISSUE TITLE
安装时出现错误

### ISSUE THREAD

**Issue by MCSeekeri** [qkqpttgf/OneDrive_SCF#24]
![](https://upload.cc/i1/2019/11/10/A9W8wM.jpg
)
都填写了SecretId和SecretKey

**Comment by MCSeekeri** [comment]
腾讯云
总览
云产品 
网站备案
网站备案
mcseekeri@outlook.com	
费用
工单
2
 
 
云函数
概览
函数服务
SCPOnedrive
正常
$LATEST
操作
函数配置函数代码触发方式运行日志监控信息
全部日志
实时近24小时
选择时间
重置
请输入requestID

2019-11-10 08:20:57	调用失败
2019-11-10 08:20:55	调用成功
2019-11-10 08:17:05	调用失败
2019-11-10 08:17:02	调用失败
2019-11-10 08:15:19	调用成功
2019-11-10 08:13:43	调用失败
2019-11-10 08:13:41	调用失败
2019-11-10 08:13:40	调用成功
2019-11-10 08:12:29	调用失败
2019-11-10 08:12:27	调用成功
2019-11-10 08:12:07	调用失败
2019-11-10 08:12:05	调用成功
请求Id：f79f0a40-034f-11ea-a909-52540014ca86
时间：2019-11-10 08:20:57运行时间:14.792ms计费时间:100ms占用内存:13.684MB
返回数据:

{"errorCode":-1,"errorMessage":"User process exit when running"}

日志:

START RequestId: f79f0a40-034f-11ea-a909-52540014ca86

Event RequestId: f79f0a40-034f-11ea-a909-52540014ca86

{

    "body": "Onedrive_ver=MS",

    "headerParameters": [],

    "headers": {

        "accept": "text\/html,application\/xhtml xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8,application\/signed-exchange;v=b3",

        "accept-encoding": "gzip, deflate",

        "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",

        "cache-control": "max-age=0",

        "connection": "keep-alive",

        "content-length": "15",

        "content-type": "application\/x-www-form-urlencoded",

        "endpoint-timeout": "15",

        "host": "service-fdby4xj6-1300363518.ap-hongkong.apigateway.myqcloud.com",

        "origin": "https:\/\/service-fdby4xj6-1300363518.ap-hongkong.apigateway.myqcloud.com",

        "referer": "https:\/\/service-fdby4xj6-1300363518.ap-hongkong.apigateway.myqcloud.com\/release\/SCPOnedrive",

        "sec-fetch-mode": "navigate",

        "sec-fetch-site": "same-origin",

        "sec-fetch-user": "?1",

        "upgrade-insecure-requests": "1",

        "user-agent": "Mozilla\/5.0 (Linux; Android 9; MIX Alpha Build\/PKQ1.180904.001; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/78.0.3904.62 Mobile Safari\/537.36",

        "x-anonymous-consumer": "true",

        "x-qualifier": "$LATEST",

        "x-requested-with": "mark.via"

    },

    "httpMethod": "POST",

    "path": "\/SCPOnedrive",

    "pathParameters": [],

    "queryString": {

        "install1": true

    },

    "queryStringParameters": [],

    "requestContext": {

        "httpMethod": "ANY",

        "identity": [],

        "path": "\/SCPOnedrive",

        "serviceId": "service-fdby4xj6",

        "sourceIp": "119.181.121.159",

        "stage": "release"

    }

}

 

{

    "memory_limit_in_mb": 128,

    "time_limit_in_ms": 3000,

    "request_id": "f79f0a40-034f-11ea-a909-52540014ca86",

    "environ": "TENCENTCLOUD_SECRETID=AKIDlL1uCdoud1-IeOflM0QhQxEBFO9ThjQnsMHQdV8zvR0PUaVCJp7bLbfooggq4DTW;TENCENTCLOUD_SECRETKEY=4QQfh4gLag4tuPEySDsPs2eKJT0sUIcoyToJA3GMsT0=;TENCENTCLOUD_SESSIONTOKEN=jYZWeRJAffzMTMFujK4G58OU8f6ZVGF801f2731afd1085e374915cc33937b3aaLl8vA2Mh9YPhA4iBSQItEPC0khuHLOqgpfLRwCGWeLvO4K_62NTxodJRF1jSHZ96i-j7baidClF9fxQvu80fxXkFSksd52LuauZJG-4eEbJryAN28AyoxdvOj_6GvbndtnVwjFye91PRnCJv8lrrUbDnP35XEV0tt4IwNdeztveiXtXmLLOxHcBSam6v1muOFk12tc4zIajhAK0BLS4C1lJGb_npYnaxOlVqoTJJxSOYjJTw2e7QyonWYOnAlHe-woyALB_2WN18snpF5XmNS27ZkL1Oi3Aarhps6n_EPvWdf-cjkaxvBTikigKw76QcYuh_GbOP0yDZFjSP7zUB1aCTJR7xzynckATH2Qvrubk;SCF_NAMESPACE=default",

    "function_version": "$LATEST",

    "function_name": "SCPOnedrive",

    "namespace": "default"

}

 

MS

Fatal error: Uncaught ArgumentCountError: Too few arguments to function updataEnvironment(), 3 passed in /var/user/functions.php on line 148 and exactly 4 expected in /var/user/scfapi.php:29

Stack trace:

#0 /var/user/functions.php(148): updataEnvironment(Array, 'SCPOnedrive', 'ap-hongkong')

#1 /var/user/index.php(113): get_refresh_token()

#2 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Array)

#3 /var/runtime/php7/bootstrap.php(189): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass))

#4 /var/runtime/php7/bootstrap.php(212): __scf_bootstrap_\__main_for_scf()

#5 {main}

  thrown in /var/user/scfapi.php on line 29

END RequestId: f79f0a40-034f-11ea-a909-52540014ca86

Report RequestId: f79f0a40-034f-11ea-a909-52540014ca86 Duration:14ms Memory:128MB MaxMemoryUsed:13.683594MB

**Comment by qkqpttgf** [comment]
啊，我的锅。
改了SCFAPI，4参数，没改这，还是3参数。
已经改了，请重新下载。

**Comment by MCSeekeri** [comment]
我重新上传了代码,依然没用
连报错都没变

**Comment by monolojue** [comment]
@MCSeekeri 同 2019年11月10日17:14:41

**Comment by qkqpttgf** [comment]
@MCSeekeri @monolojue I am Very Sorry（想死……
这次我自己安装测试了，可以了

**Comment by MCSeekeri** [comment]
~~按M安轨！~~
修改了就好,话说这个新功能挺好用的



来自MCSeekeri的Outlook或Google邮箱
