### ISSUE TITLE
出错 Please create SecretId & SecretKey and add them in the environments First!（已在环境变量中填写 SecretId & SecretKey）

### ISSUE THREAD

**Issue by creboy** [qkqpttgf/OneDrive_SCF#25]
返回数据:

{"isBase64Encoded":false,"statusCode":500,"headers":{"Content-Type":"text\/html"},"body":"<html><meta charset=utf-8><body><h1>Error<\/h1><p>Please <a href=\"https:\/\/console.cloud.tencent.com\/cam\/capi\" target=\"_blank\">create SecretId & SecretKey<\/a> and add them in the environments First!<br><\/p><\/body><\/html>"}

日志:

START RequestId: 0deb3fc6-0468-11ea-befa-5254000dcd5e

Event RequestId: 0deb3fc6-0468-11ea-befa-5254000dcd5e

{

    "headerParameters": [],

    "headers": {

        "accept": "text\/html,application\/xhtml xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8,application\/signed-exchange;v=b3",

        "accept-encoding": "gzip, deflate, br",

        "accept-language": "zh-CN,zh;q=0.9",

        "cache-control": "max-age=0",

        "connection": "keep-alive",

        "endpoint-timeout": "15",

        "host": "service-mq1j4bmw-1259350176.ap-hongkong.apigateway.myqcloud.com",

        "sec-fetch-mode": "navigate",

        "sec-fetch-site": "none",

        "sec-fetch-user": "?1",

        "upgrade-insecure-requests": "1",

        "user-agent": "Opera\/9.80 (Windows NT 6.0) Presto\/2.12.388 Version\/12.14",

        "x-anonymous-consumer": "true",

        "x-qualifier": "$LATEST"

    },

    "httpMethod": "GET",

    "path": "\/A3432",

    "pathParameters": [],

    "queryString": [],

    "queryStringParameters": [],

    "requestContext": {

        "httpMethod": "ANY",

        "identity": [],

        "path": "\/A3432",

        "serviceId": "service-mq1j4bmw",

        "sourceIp": "61.133.118.201",

        "stage": "release"

    }

}

 

{

    "memory_limit_in_mb": 128,

    "time_limit_in_ms": 3000,

    "request_id": "0deb3fc6-0468-11ea-befa-5254000dcd5e",

    "environ": "TENCENTCLOUD_SECRETID=AKIDi1FEUn24zuUO4iuwf4oo69wviLXVC1otZMhs57Wk6Y4Wm1bv-JuqQOQC81gWt0kl;TENCENTCLOUD_SECRETKEY=CHzpGfaW Fr1bQ1cutcIJiUU01k9jsUhzZTGcPMUpRo=;TENCENTCLOUD_SESSIONTOKEN=em3ZT3sFmucB2aIyNmBBb43PgQs499Iz42f5f218fa32c67d13f76876ecd33cd2FLXPY-

**Comment by MCSeekeri** [comment]
hmmm
您确定是输对了吗是大写的i
而且这个日志似乎看不出什么东西

**Comment by qkqpttgf** [comment]
你是添加了SecretId 跟 SecretKey 这2个，还是添加了SecretId & SecretKey这一个？

**Comment by creboy** [comment]
> 你是添加了SecretId 跟 SecretKey 这2个，还是添加了SecretId & SecretKey这一个
都添加了

**Comment by creboy** [comment]
是在环境变量里的KEY和Value里分别填写SecretId & SecretKey吗

**Comment by creboy** [comment]
问题解决了，在环境变量里的KEY和Value里分别填写SecretId & SecretKey，哈哈
