### ISSUE TITLE
后台管理问题

### ISSUE THREAD

**Issue by Acordarse** [qkqpttgf/OneDrive_SCF#26]
后台管理页面点击修改后，管理员密码会被移除

**Comment by MCSeekeri** [comment]
这是你自己把管理员密码删了吧...

**Comment by Acordarse** [comment]
> 这是你自己把管理员密码删除了吧...

经测试，只有密码为 `0` 的时候会出现这个bug

**Comment by MCSeekeri** [comment]
有意思,我测试一下试试

**Comment by qkqpttgf** [comment]
收到。
判断的时候，0跟空都是假的所以清除了。
等下修改。
----------------
已经修改，直接更新试试。
