### ISSUE TITLE
安装时报错 AuthFailure.SignatureFailure

### ISSUE THREAD

**Issue by judiw** [qkqpttgf/OneDrive_SCF#28]
在选择Onedrive版本后报错：

Error
AuthFailure.SignatureFailure
The provided credentials could not be validated. Please check your signature is correct.

function_name:Onedrive
Region:ap-hongkong
namespace:default

**Comment by qkqpttgf** [comment]
这边几秒钟前，全新下载代码安装，没有这个问题~
你看readme，加QQ群

**Comment by judiw** [comment]
找到解决方法了，只要把domain_path这个环境变量删掉再运行就不会报错了

**Comment by qkqpttgf** [comment]
> 找到解决方法了，只要把domain_path这个环境变量删掉再运行就不会报错了

呃，这样的话，我明白错在哪了。
那domain_path的机制我要改一改了，~~明天再说~~刚刚改掉了，更新前注意。
