### ISSUE TITLE
腾讯云发来API付费的短信

### ISSUE THREAD

**Issue by SeqCrafter** [qkqpttgf/OneDrive_SCF#32]
请问，这个onedrive的云函数会收到影响吗

**Comment by qkqpttgf** [comment]
会的，外出流量要收费了，应该是每月8毛/G。具体可以查看腾讯的文档。

**Comment by SeqCrafter** [comment]
> 会的，外出流量要收费了，应该是每月8毛/G。具体可以查看腾讯的文档。

嗯，不过第一年有调用次数和出流量的免费额度，下一年就要收费了
