### ISSUE TITLE
登录能够放在方框这个位置吗，左上角不太习惯，也很小

### ISSUE THREAD

**Issue by liushaoyang** [qkqpttgf/OneDrive_SCF#38]
![image](https://user-images.githubusercontent.com/40416571/69896938-c24fb780-137f-11ea-8c84-15e28005f9e6.png)

**Comment by liushaoyang** [comment]
登录放在列表的右上角

**Comment by qkqpttgf** [comment]
那我放大点可以吗？
原来那个位置，以后想加什么就跑下去了点不到了……所以把它做横的了。

**Comment by liushaoyang** [comment]
> 那我放大点可以吗？
> 原来那个位置，以后想加什么就跑下去了点不到了……所以把它做横的了。

可以做个绝对定位，那样就不会跑了。没事，就是再左上角不太友好，不用改，不太影响使用。
