### ISSUE TITLE
请问，我该如何实现自动上传图片并返回对应外链的这种操作

### ISSUE THREAD

**Issue by SeqCrafter** [qkqpttgf/OneDrive_SCF#4]

**Comment by qkqpttgf** [comment]
图床API？
我特意在90~95行附近判断referer，不是本站的话$config['current_url']就是空值，然后在470行判断$config['current_url']是空的话不保存文件，然后在481行拼接URL的时候$config['current_url']是空的话拼出来的URL只有后面的md5文件名，获取不到外链（大写的尴尬）
我拒绝从别的地方上传过来~~你要自己改的话，要改这3个地方。

**Comment by SeqCrafter** [comment]
好的，感谢
