### ISSUE TITLE
安装中出现错误

### ISSUE THREAD

**Issue by ciye12138** [qkqpttgf/OneDrive_SCF#42]
Error
InvalidParameterValue
A value specified in `Region` is not valid, is unsupported, or cannot be used.

function_name:onedrive
Region:bj
namespace:default

求各位大佬解答！

**Comment by qkqpttgf** [comment]
SCF还没提供Region，所以程序不知道[我在哪]，只能从长链接里面截取来用，但北京那边要的是ap-beijing而不是bj，所以不能用。
你可以在其它地区使用。或等SCF明年提供。

**Comment by ciye12138** [comment]
> SCF还没提供Region，所以程序不知道[我在哪]，只能从长链接里面截取来用，但北京那边要的是ap-beijing而不是bj，所以不能用。
> 你可以在其它地区使用。或等SCF明年提供。

谢谢大佬
