### ISSUE TITLE
get token 错误 返回‘‘有误！微软 code 为空！’’

### ISSUE THREAD

**Issue by wrhsd1** [qkqpttgf/OneDrive_SCF#5]
大佬 不成功啊 到 Get a refresh_token 这一步，登陆了微软账号后返回
“” 如果长时间未跳转，请点击：继续安装
有误！微软 code 为空！“”
并没有得到代码 什么原理啊 
账户用的是申请的教育网 1T 的 office 账户，用客户端和网页版上传下载都没问题 但是操作到这一步就返回 有误！微软 code 为空！

**Comment by qkqpttgf** [comment]
应该是你的账户没给权限，你贴一下出错时你的地址栏里面的内容。

**Comment by wrhsd1** [comment]
应该是邮箱没有管理员 
https://scfonedrive.github.io/?error=invalid_client&error_description=AADSTS650051%3a+Using+application+%27one_scf%27+is+currently+not+supported+for+your+organization+szjm.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+szjm.edu.cn+before+the+application+one_scf+can+be+provisioned.%0d%0aTrace+ID%3a+38212218-ac30-4766-b4a7-d08e2b131300%0d%0aCorrelation+ID%3a+f4ce4574-7df1-4201-88e8-46bdbd48013d%0d%0aTimestamp%3a+2019-09-20+07%3a54%3a03Z&state=https%3a%2f%2fservice-kuyqeehy-1252054573.ap-hongkong.apigateway.myqcloud.com%2frelease%2fwcloud%2f
