### ISSUE TITLE
onedrive_scf的更新问题

### ISSUE THREAD

**Issue by HYwooo** [qkqpttgf/OneDrive_SCF#50]
使用腾讯云scf部署，进入管理--一键更新

然后返回主页面，
此时主页面文件列表消失。

用原文件覆盖upload后救回

另：onemanager和这个scf是什么关系？

**Comment by qkqpttgf** [comment]
你看一眼说明啊……都说转到那边去了，升级也是升级到那边去。
那边是多盘，你要去添加你的网盘。
