### ISSUE TITLE
请问如何实现https自动跳转？

### ISSUE THREAD

**Issue by judiw** [qkqpttgf/OneDrive_SCF#6]

**Comment by qkqpttgf** [comment]
（这个不是必须要的）
目前程序中不能在服务端判断是http还是https，现在只能在网页里面加javascript来跳，你可以搜一下代码。
我已经跟腾讯SCF反馈了，看什么时候加入https状态，这样在服务端就可以做301了。

**Comment by judiw** [comment]
好的，感谢
