### ISSUE TITLE
大佬请问怎么让非管理员有上传权限。

### ISSUE THREAD

**Issue by ghost** [qkqpttgf/OneDrive_SCF#7]

**Comment by qkqpttgf** [comment]
1，首先，我有写一个imgup_path ，不去看下readme.md再说？不过文件大小限制4M。
2，上传大文件要从微软得到一个超长的目标URL，然后对着它上传，但我怀疑里面有token相关的东西，所以我不放开给非管理员，你要弄的话，可以自己修改代码。

**Comment by ghost** [comment]
图床这个我修改着试过，上传失败-_-

**Comment by qkqpttgf** [comment]
不可能啊，你看我demo的，很多人尝试过上传图片给我，还有小视频

**Comment by ghost** [comment]
那样搞来搞去麻烦不说还有上传错误的可能，我直接把删除键给删除了，管理员密码直接放根目录readme，哈哈哈哈红红火火恍恍惚惚

**Comment by qkqpttgf** [comment]
> 那样搞来搞去麻烦不说还有上传错误的可能，我直接把删除键给删除了，管理员密码直接放根目录readme，哈哈哈哈红红火火恍恍惚惚

那重命名呢？移动呢？动一下你文件就乱了。
还有就算删除了删除按钮，后台还是可以处理删除操作的，你要把删除文件这个处理去掉。

**Comment by ghost** [comment]
重命名和移动都没问题，我只删除了删除键，需要删除的文件我到OneDrive移动客户端删除，现在使用体验良好，

**Comment by qkqpttgf** [comment]
我是说别人"帮"你重命名一下，你完蛋了。
别人可以手动添加删除键，或用工具提交，把你文件删光。

**Comment by qkqpttgf** [comment]
今天开了个分支，游客上传大文件，https://github.com/qkqpttgf/OneDrive_SCF/tree/GuestUploadBigFile

**Comment by ghost** [comment]
666666
