### ISSUE TITLE
自定义域名后，为什么文件无法下载！？

### ISSUE THREAD

**Issue by hyy34** [qkqpttgf/OneDrive_SCF#8]
![TIM截图20191006220305](https://user-images.githubusercontent.com/26433019/66270483-d9de5880-e886-11e9-8a8b-8efdbcbc8087.jpg)
目测，应该是没解析出来OD的地址。。不添加自定义域名访问，下载的时候连接都是自动解析出https://xxx-my.sharepoint.com/xxx 这种的，但是添加自定义域名后，下载链接都是http://自定义域名/文件，所以无法下载，请问如何解决呢！？？
是我域名解析有问题！？
我就是把域名CNAME 到xxxx.ap-hongkong.apigateway.myqcloud.com，难道不对吗！？？

**Comment by hyy34** [comment]
测试下了，chrome，除了mp4文件，其余都是无规律无法下载，可能无法下载，但是刷新一次就能解析出来源地址了。。。但是，mp4的文件一直都不可以！！

**Comment by qkqpttgf** [comment]
这边一直用的chrome，你的HyY里面的mp4我下载没问题，图片怎么加？
你的图片里面显示，检测到302跳转，说明OD的地址已经解析出来了，但它不去跳，我也没办法。
