### ISSUE TITLE
可以设置默认按照修改时间降序排列吗？

### ISSUE THREAD

**Issue by yoogg** [qkqpttgf/OneDrive_SCF#9]
把最新修改的文件始终排在前名，现在最新版的好像也不能排序。
现在默认排序是从旧到新排列的，最老的文件在上面，新文件在最底部，查看很不方便

**Comment by qkqpttgf** [comment]
从9/20号开始就可以排序了。
我时间跟大小都默认从小到大排序，所以新文件就在最下面了。
刚刚修改了下，可以多次点击，正反排序。
